== Partner Requirements

=== Domain name

When delivering PCF Administrator training using Google Cloud Platform (GCP), a partner needs to have a registered domain name, from which subdomains can be created for each student. For example, assuming the domain name `example.org`, and a student named John Smith
  with username `jsmith`, their PCF instance domain name would have the suffix `jsmith.example.org`.

=== Tooling

The installation of PCF on GCP requires:

- the use of the gcloud CLI, which is part of the Google Cloud SDK
- the tool https://www.terraform.io/[Terraform^], to setup the infrastructure
- the use of a Pivotal project containing Terraform scripts designed for PCF

For convenience, a VM image in Google Cloud Storage (named _{image_cloudstorage_file}_) has been prepared with the above items pre-installed:

 - https://cloud.google.com/sdk/[Google Cloud SDK^]
 - https://releases.hashicorp.com/terraform/0.8.4/[Terraform v0.8.4^]
 - a copy of the https://github.com/pivotal-cf/terraforming-gcp[terraforming-gcp project^] https://github.com/pivotal-cf/terraforming-gcp/releases/tag/v0.6.0[v0.6.0 release^] installed at `~/terraforming-gcp`

Students are free to setup their local machines with the above tools on their own.  For convenience, they can opt instead to instantiate a VM with the tools pre-installed.  Instructions are provided in the lab.


=== Additional Requirements

Furnish each student (or pair of students):

. a GCP project that the student will own, with quota configured appropriately to deploy PCF.  See <<Suggested Quota>>.

. a private key and certificate pair to be used in conjunction with SSL configuration of the CF installation.  See <<Generating SSL Private Key and Certificate for Student>>.

NOTE: after students finish the terraform part of the installation, they will have a Google Cloud DNS zone configured for their subdomain.  Instructors will need to create an NS record for each subdomain.
