== Partner Requirements

=== Tooling

The installation of PCF on GCP requires the following client software, which students are instructed to install on their machines:

- the https://cloud.google.com/sdk/[Google Cloud SDK^], which provides the `gcloud` CLI
- the use of a Pivotal project containing Terraform scripts designed for PCF, named https://github.com/pivotal-cf/terraforming-gcp[terraforming-gcp^].  This course is based on  https://github.com/pivotal-cf/terraforming-gcp/releases/tag/v0.6.0[release version 0.6.0^]
- Hashicorp's https://www.terraform.io/[Terraform^].  Be sure to use https://releases.hashicorp.com/terraform/0.8.4/[version 0.8.4^]

=== Domain name

Have a registered domain name, from which students can create subdomains.

For example, assuming the domain name `example.org`, and a student named John Smith with username `jsmith`, their PCF instance domain name would have the suffix `jsmith.example.org`.

This maps nicely to the concept of an "env_name", one of the variables used by the terraforming-gcp project.

=== Requirements

Furnish each student (or pair of students):

. a GCP project that the student will own, with quota to deploy PCF configured appropriately for the region the class will be delivered in.  See <<Suggested Quota>>.

. a private key and certificate pair to be used in conjunction with SSL configuration of the CF installation.  See <<Generating SSL Private Key and Certificate for Student>>.

NOTE: After students finish the terraform part of the installation, they will have a Google Cloud DNS zone configured for their subdomain.  Instructors will need to create an NS record for each subdomain.
