== Terraforming GCP

Welcome!

Your instructor has prepared the following on your behalf:

- A Google Cloud Project
- A private key file, and a corresponding SSL certificate file, to be used in conjunction with installing PCF


=== Logging in to GCP

- in a browser, navigate to the https://console.cloud.google.com/[GCP console^] and log in.
- navigate to your project by selecting your project name from the projects "dropdown" in the page header.

=== Installing the Requisite Client Tools

To install PCF on GCP, you'll need the following items:

- the https://cloud.google.com/sdk/[Google Cloud SDK^], which provides the `gcloud` CLI
- the use of a Pivotal project containing Terraform scripts designed for PCF, named https://github.com/pivotal-cf/terraforming-gcp[terraforming-gcp^].  This course is based on  https://github.com/pivotal-cf/terraforming-gcp/releases/tag/v0.6.0[release version 0.6.0^]
- Hashicorp's https://www.terraform.io/[Terraform^].  Be sure to use https://releases.hashicorp.com/terraform/0.8.4/[version 0.8.4^]

==== Instructions

Using the above links:

. Download and install the Google Cloud SDK (you can verify the installation with the command `gcloud --version`)
. Download and unzip the terraforming-gcp project, release version 0.6.0, to a subfolder of your home directory
. Download and install Hashicorp's Terraform, version 0.8.4 (you can verify the installation with the command `terraform --version`)

Log in to google cloud project from the command line, using the gcloud sdk

[source.terminal]
----
gcloud init
----

* When prompted to select an account, select option 2: _Log in with a new account_, and follow the instructions to authenticate
* Enter your project id when prompted for it
* Select the default region where resources should be created (us-central1)


=== Initial Configuration

. Setup project-wide SSH key: the instructions to setup a project-wide SSH key are part of the Pivotal official documentation, and available http://docs.pivotal.io/pivotalcf/customizing/gcp-prepare-env.html#keys[here^].  _Please follow step 4 only_.

+
. Create a service account and download keyfile:
+
[source.terminal]
----
gcloud iam service-accounts create terraform-service-account
----
+
[source.terminal,subs="attributes+"]
----
gcloud iam service-accounts keys create '{key_json_filename}' --iam-account 'terraform-service-account@{project_id}.iam.gserviceaccount.com'
----
+
[source.terminal,subs="attributes+"]
----
gcloud projects add-iam-policy-binding {project_id} --member 'serviceAccount:terraform-service-account@{project_id}.iam.gserviceaccount.com' --role 'roles/editor'
----
+
NOTE: If you prefer, you can follow along http://docs.pivotal.io/pivotalcf/customizing/gcp-prepare-env.html#iam_account[here^] to create the account and download the key via the google cloud console web-based ui  ..but then don't forget to issue the third command above to add the IAM policy binding to give the account the role _roles/editor_

. Enable access to three GCP APIs: Resource Manager API, Cloud DNS API, Identity & Access Management API.
   See http://docs.pivotal.io/pivotalcf/customizing/gcp-prepare-env.html#enable_compute_resource_api[these instructions^] for how to do this for the Resource Manager API. Don't forget to also enable the Google Cloud DNS API, and Google Identity and Access Management API in a similar fashion.

=== Prepare and run Terraform scripts

Below is a distillation of the instructions from the https://github.com/pivotal-cf/terraforming-gcp[terraforming-gcp project's README file^]:

. Navigate to the terraforming-gcp project release:
+
[source.terminal]
----
cd ~/terraforming-gcp
----

. Setup your `terraform.tfvars` file as described in the project's README file (you may use this link:artifacts/terraform.tfvars[template^]):
+
You'll need to supply values for the following variables:

 - `project`: your project id ({project_id})
 - `region`: us-central1
 - `zones`: ["us-central1-a", "us-central1-b", "us-central1-c"]
 - `env_name`: your username, e.g. {env_name}
 - `opsman_image_url`: https://storage.googleapis.com/ops-manager-us/pcf-gcp-1.9.2.tar.gz
+
TIP: to install a newer version of the Ops Manager, visit the https://network.pivotal.io[Pivotal Network^]), and under _Operations Manager_, look for the _Pivotal Cloud Foundry Ops Manager YAML for GCP_

 - `dns_suffix`: provided by partner, e.g. {domain_name}
 - `ssl_cert` : copy and paste the supplied SSL certificate
 - `ssl_cert_private_key` : copy and paste the suplied SSL private key
 - `service_account_key` : copy and paste the contents of the service account key file you created above (_{key_json_filename}_)

. From the `terraforming-gcp` directory, run `terraform plan` to see what you're about to create.

. Run `terraform apply` and watch it create the IAAS foundation that will be used to install Cloud Foundry.


=== Validate Installation

The Terraform scripts create the infrastructure necessary to proceed with the installation of the bosh director, the elastic runtime tile, and PCF services tiles.  This infrastructure includes: a network, three subnetworks, static IP addresses, load balancers, firewall rules, routes, backend services, SSL cert, forwarding rules, health checks, instance groups, Ops Manager image, Ops Manager VM instance, Ops Manager service account, buckets in google storage for blobstores, hosted zone for env-name + DNS suffix, and all necessary DNS entries within the hosted zone.

In your browser, use the google cloud console to navigate to the networking section and verify that the above have been created for you.

NOTE: this Terraform script sets up three availability zones, and three separate subnets, one each for ops VMs (Ops Manager and bosh director), elastic runtime, and Cloud Foundry services

Congratulations, you have deployed the infrastructure necessary to proceed with the installation.
