= BOSH Troubleshooting
Eitan Suez <esuez@pivotal.io>
v0.1, 2017
:project_id: {{project_id}}
:domain_name: {{domain_name}}
:env_name: {{env_name}}
:director_ip_address: {{director_ip_address}}
:region: {{region}}

Estimated time:  1 hour

= Requirements

Lab Requirements

= What you will learn

* How to troubleshoot problems with BOSH

= Exercises

== Going Deeper with Ops Manager

. In the Ops Manager, select the GCP _tile_.  We need to retrieve some information:
.. the Ops Manager IP address: navigate to the _Status_ tab, note the IP address for the Ops Manager Director
.. navigate to the _Credentials_ tab, click the link to the director credentials, note the identity and password displayed in the json response.

. verify that you can ssh into the Ops Manager with:
+
[source.terminal]
----
gcloud compute ssh ubuntu@{{env_name}}-ops-manager
----
+
NOTE: The above command dynamically creates a key pair for logging in to the VM
+
The bosh client is pre-installed on Ops Manager VM.  For security, the bosh director VM is usually not made accessible from the outside world.  The Ops Manager VM serves as a bastion VM from which we can communicate with the bosh director.

. Target, and login to the bosh director:
+
[source.terminal]
----
bosh --ca-cert /var/tempest/workspaces/default/root_ca_certificate target {{director_ip_address}}
----
+
When prompted to log in, enter `director` for the user name, and the previously noted secret for the password.

. Invoke the following command:
+
[source.terminal]
----
bosh deployments
----
+
The response should be empty at the moment, as we have not yet used the bosh director to deploy anything.

You may now log out of the Ops Manager.

Congratulations, you have verified the proper functioning of the bosh director and are now ready to move on to installing the elastic runtime (our next lab).
