= Terraforming GCP

Welcome!

Your instructor has prepared the following on your behalf:

- A Google Cloud Project
- A private key and SSL certificate to be used in conjunction with installing PCF
- A VM Image with the software necessary to install Cloud Foundry


== Logging in to GCP

- in a browser, navigate to the https://console.cloud.google.com/[GCP console] and log in.  Next, navigate to your project.

- create instance of image: locate image, create instance _TODO: supply instructions_

- ssh in to your instance:
+
----
gcloud compute ssh ubuntu@[instance-name]
----
+
- log in to google cloud project from the command line, using the gcloud sdk
+
----
gcloud init
----
+

_TBD: insert instructions for logging in to gcloud project_

== Initial Configuration

. setup project-wide ssh key:
  the instructions to setup a project-wide ssh key are part of the pivotal official documentation, and available here
  (please follow step 4 only):
    http://docs.pivotal.io/pivotalcf/customizing/gcp-prepare-env.html#keys
+
. setup a service account and download keyfile:
+
[source,bash,linenums,subs="attributes+"]
----
gcloud iam service-accounts create terraform-service-account
gcloud iam service-accounts keys create "{key_json_filename}" --iam-account "terraform-service-account@{project_id}.iam.gserviceaccount.com"
gcloud projects add-iam-policy-binding {project_id} --member 'serviceAccount:terraform-service-account@{project_id}.iam.gserviceaccount.com' --role 'roles/editor'
----
+
NOTE: if you prefer, you can follow along here to create the account and download the key via the google cloud console web-based ui: http://docs.pivotal.io/pivotalcf/customizing/gcp-prepare-env.html#iam_account ..but then don't forget to issue the third command above to add the iam policy binding to give the account the role "roles/editor"

. enable access to three GCP APIs: Resource Mgr API, Cloud DNS API, Identity and Access Management API.
   See http://docs.pivotal.io/pivotalcf/customizing/gcp-prepare-env.html#enable_compute_resource_api[these instructions] for how to do this for the Resource Manager API. Don't forget to also enable the Google Cloud DNS API, and Google Identity and Access Management API.

== Prepare and run terraform scripts:

Below is a distillation of the instructions from the https://github.com/pivotal-cf/terraforming-gcp[terraforming-gcp project's readme file]:

. navigate to the terraforming-gcp project release:
+
----
cd ~/terraforming-gcp
----

. setup your `terraform.tfvars` file as described in the project's readme file:
+
You'll need to supply the following:

 - `project`: your project id ({project_id})
 - `region`: us-central1
 - `zones`: ["us-central1-a", "us-central1-b", "us-central1-c"]
 - `env_name`: your username, e.g. {username}
 - `opsman_image_url`: https://storage.googleapis.com/ops-manager-us/pcf-gcp-1.9.2.tar.gz
 - `dns_suffix`: provided by partner, e.g. {domain_name}
 - `ssl_cert` : copy and paste the supplied SSL certificate
 - `ssl_cert_private_key` : copy and paste the suplied SSL private key
 - `service_account_key` : copy and paste the contents of the service account key file you created above ({key_json_filename})

. from the `terraforming-gcp` directory, run `terraform plan` to see what you're about to create.

. run `terraform apply` and watch it create the IAAS foundation that will be used to install Cloud Foundry.


== Validate Installation

The terraform scripts create the infrastructure necessary to proceed with the installation of the bosh director, the elastic runtime tile, and PCF services tiles, which includes: a network, three subnetworks, static ip addresses, load balancers, firewall rules, routes, backend services, ssl cert, forwarding rules, health checks, instance groups, ops manager image, ops manager vm instance, ops manager service account, buckets in google storage for blobstores, hosted zone for env-name + dns suffix, and all necessary dns entries within the hosted zone.

In your browser, use the google cloud console to navigate to the networking section and verify that the above have been created for you.

NOTE: this terraform script sets up three availability zones, and three separate subnets, one each for ops vms (ops manager and bosh director), elastic runtime, cloud foundry services

Congratulations, you have deployed the infrastructure necessary to proceed with the installation.
